version: '3.8'

services:
  # NUBI Agent Core
  agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile.agent
    container_name: nubi-agent
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CLICKHOUSE_URL=${CLICKHOUSE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - agent_data:/app/data
    networks:
      - nubi-network
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
      - clickhouse

  # API Service
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: nubi-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - nubi-network
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nubi-postgres
    environment:
      - POSTGRES_DB=nubi
      - POSTGRES_USER=${DB_USER:-nubi}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - nubi-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: nubi-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - nubi-network
    restart: unless-stopped

  # ClickHouse Analytics
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: nubi-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ../analytics/clickhouse-setup.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - CLICKHOUSE_DB=analytics
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    networks:
      - nubi-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nubi-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/ssl:/etc/nginx/ssl
    networks:
      - nubi-network
    depends_on:
      - api
      - agent
    restart: unless-stopped

volumes:
  agent_data:
  postgres_data:
  redis_data:
  clickhouse_data:

networks:
  nubi-network:
    driver: bridge
