version: '3.8'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.agent
    command: npm test
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgres://test:test@postgres:5432/test
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - test-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    networks:
      - test-network

  redis:
    image: redis:7-alpine
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
