apiVersion: v1
kind: Service
metadata:
  name: nubi-agent
  namespace: production
spec:
  selector:
    app: nubi-agent
    version: green
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer

