# Prometheus Configuration for NUBI Agent Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'nubi-agent'
    environment: 'production'

# Alert rules
rule_files:
  - '/etc/prometheus/alerts.yml'

# AlertManager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

  # NUBI Agent metrics
  - job_name: 'nubi-agent'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
          - 'nubi-agent:8080'
        labels:
          service: 'nubi-agent'
          component: 'core'

  # ElizaOS metrics
  - job_name: 'elizaos'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'elizaos:3001'
        labels:
          service: 'elizaos'
          component: 'runtime'

  # ClickHouse metrics
  - job_name: 'clickhouse'
    static_configs:
      - targets:
          - 'clickhouse:9363'
        labels:
          service: 'clickhouse'
          component: 'database'

  # Redis metrics (via redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis-exporter:9121'
        labels:
          service: 'redis'
          component: 'cache'

  # Platform API metrics
  - job_name: 'platform-apis'
    static_configs:
      - targets:
          - 'telegram-api:8081'
          - 'discord-api:8082'
          - 'twitter-api:8083'
        labels:
          service: 'platform-api'

  # Socket.IO metrics
  - job_name: 'socketio'
    static_configs:
      - targets:
          - 'socketio:3002'
        labels:
          service: 'socketio'
          component: 'realtime'

  # Kubernetes metrics (if deployed on k8s)
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
