version: '3.8'

services:
  agent:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DATABASE_URL=postgres://nubi:password@postgres:5432/nubi
      - REDIS_URL=redis://redis:6379
      - CLICKHOUSE_URL=http://clickhouse:8123
      - OPENAI_API_KEY=${OPENAI_API_KEY:-test}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-test}
    ports:
      - "8080:8080"

  postgres:
    environment:
      - POSTGRES_PASSWORD=password

  clickhouse:
    environment:
      - CLICKHOUSE_PASSWORD=password
