apiVersion: apps/v1
kind: Deployment
metadata:
  name: nubi-agent-green
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nubi-agent
      version: green
  template:
    metadata:
      labels:
        app: nubi-agent
        version: green
    spec:
      containers:
      - name: agent
        image: ghcr.io/dexploarer/dex-analytics-agent:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: nubi-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: nubi-secrets
              key: redis-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
